### PR TITLE
Fix Kotlin array attribute

### PR DESCRIPTION
**Pull request by sathieu**
See https://docs.spring.io/spring-framework/docs/5.3.13/reference/html/languages.html#annotation-array-attributes

### CODE REVIEW

**Comment by sathieu** [comment]
@garronej Please merge, this fixes the build 🚀 !

**Comment by sathieu** [comment]
@garronej Could you please tag v0.8 :pray:? It'll allow to merge https://github.com/InseeFrLab/helm-charts/pull/25 with a minimum required version.

**Comment by garronej** [comment]
@olevitt

**Comment by garronej** [comment]
👍🏻

**Pull request merged**
