### PR TITLE
Run image as non-root

### PR DESCRIPTION
**Pull request by sathieu**
Reduce the attack surface, and allow to run the image
with strict `PodSecurity`.

Similar to https://github.com/InseeFrLab/onyxia-web/pull/279.

### CODE REVIEW

**Comment by sathieu** [comment]
@garronej Please review 🙏 .

**Comment by olevitt** [comment]
@sathieu please tag me instead of Jo for things related to the API.
I will take a look at this soon, thanks for your contribution.
On this subject, we should improve the base docker image used. It currently uses a JDK image instead of a JRE which is unecessary and could be a liability. Apparently there is no JRE image published anymore, you have to manually build a custom JRE when building the app. We may want to switch to relying on Spring boot builder to simplify build. But we will need to find a way to add kubectl and helm to the image.

**Comment by sathieu** [comment]
Thanks @olevitt. I don't know anything about Spring boot builder. As an alternative, there are eclipse-temurin images (from adoptium, formerly adoptjdk), which provides a `17-jre` tag (`== 17.0.1_12-jre-focal`)

Refs:

- https://hub.docker.com/_/eclipse-temurin/
- https://github.com/docker-library/docs/blob/master/eclipse-temurin/README.md#supported-tags-and-respective-dockerfile-links

**Comment by olevitt** [comment]
@sathieu I took the liberty of changing the base image to eclipse-temurin:17-jre after having tested it succesfully locally. It still generates a huge image but at least it's smaller than the previous one.  
Thanks :+1:

**Comment by sathieu** [comment]
Great!

**Pull request merged**
