### PR TITLE
Add namespace metadata

### PR DESCRIPTION
**Pull request by olevitt**
This PR adds user metadata to the namespace at each onboard (see https://github.com/InseeFrLab/onyxia/issues/752).  
The list of claims to be added is configurable at region's level.  
This is in addition to the already existing support for static labels & static annotations.

### CODE REVIEW

**Comment by olevitt** [comment]
Labels have to much restrictions on what they can contain (both on key and values) so let's use annotations instead

**Comment by olevitt** [comment]
This PR is up for review, feedback is welcome

**Review by micedre — APPROVED** [review]

**Comment by olevitt** [comment]
There is currently a regression on events as each onboarding call will trigger a `namespace created` event even if the namespace already exists. Working on it

**Comment by alexisdondon** [comment]
I ve tested the MR on the main scenario seems to work for me

**Pull request merged**
