### PR TITLE
Disable refresh and add some warning to documentation

### LINKED ISSUE #360: Change default catalog refresh timer
Currently Onyxia refresh the catalogs every 5 minutes (see https://github.com/InseeFrLab/onyxia-api?tab=readme-ov-file#catalogs-configuration- `catalogs.refresh.ms`).  
There are some caveats associated with catalog refreshs :  
* In case you have multiple API pods, having one refreshed and not the other means they may be desynched resulting in user facing bugs
* Refresh may fail due to a temporary failure in registry  
* Refreshing the catalogs and fetching all packages every x minutes may cause some heavy load (see #358 for possible mitigation)
* Periodic refresh on catalogs you don't maintain yourself may result in app breaking unexpectedly  

I suggest we disable the refresh by default (setting `0` to `catalogs.refresh.ms` by default) while still allowing admin to override it. I also suggest we document the caveats.

### PR DESCRIPTION
**Pull request by olevitt**
Fixes #360

### CODE REVIEW

**Review by odysseu — APPROVED** [review]

**Review by johnksv — COMMENTED** [review]
I think this a OK workaround for now.
Short term: Maybe a admin endpoint to force catalog refresh could be nice (so one could port forward to the pod and trigger refresh)?
Long term: Would have to think about some solution to keep replicas in sync. Maybe you have some ideas.

**Comment by olevitt** [comment]
> Short term: Maybe a admin endpoint to force catalog refresh could be nice (so one could port forward to the pod and trigger refresh)? 

It could be doable, maybe by restricting traffic to localhost only and providing a convenience sh script within the image. But I'm not sure that's worth it and more usable than deleting the pod

> Long term: Would have to think about some solution to keep replicas in sync. Maybe you have some ideas.

I think for that it will be partly related to https://github.com/InseeFrLab/onyxia-api/issues/359.  
I think implementing some distributed cache like redis may be overkill but having the catalog served internally by the API or by a side pod / container may solve refresh inconsistencies by having the catalog set to a specific docker image tag for example

**Comment by alexisdondon** [comment]
One possible way to deal with multiple pod with less pain could be https://medium.com/@bectorhimanshu/how-to-create-a-scheduled-task-using-a-cron-job-in-spring-boot-a1987e679d60 a cron task to plan a refrehs of catalogs at same time on all pods.

If a pod restart and in the sametime catalogs was updated between two expressions there is no magic instead you deal with some kind of creation timestamp in helm metadata

**Comment by alexisdondon** [comment]
Still another way little more tricky but will completely answer to the need is to add a distributed cache solution in spingboot one could be https://infinispan.org/docs/stable/titles/spring_boot/starter.html.

the embedded mode need no installation of redis or persistent caching solution, the embedded mode need a springboot configuration and the pods speak with each others to manage the same cache.

**Pull request closed without merging**
